<?php
/**
 * Implements hook_block_info().
 */
function asobitico_module_block_info() {
  $blocks = array();
  $blocks['preguntas_frecuentes'] = array(
    'info' => t('Frequently asked questions by country'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function asobitico_module_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'preguntas_frecuentes' :
      $block['content'] = array(
        '#markup' => asobitico_module_preguntas_frecuentes_por_paises(),
        '#attached' => array(
            'js' => array(
              drupal_get_path('module', 'asobitico_module') . '/js/custom_accordion.js',
              'https://code.jquery.com/ui/1.9.2/jquery-ui.js',
          ),
            'css' => array(
              drupal_get_path('module', 'asobitico_module') . '/css/custom_accordion.css',
          ),
        ),
      );
    break;
  }
  
  return $block;
}


function asobitico_module_preguntas_frecuentes_por_paises(){
  
  global $base_url;
  //extraer el termino Costa Rica del vocabulario (pais)
  //13 es el identificador para Costa Rica, NOTA: no cambiar este id en administracion
  //********** ACORDION NACIONAL *******
  $costa_rica = taxonomy_term_load(13);
  $imagen = "<img src='" . $base_url . '/sites/default/files/banderas/' . $costa_rica->field_imagen[LANGUAGE_NONE][0]['filename'] . "'>";
  $bloque_nacional = '<div id="pf-nacional"><h3><strong>'.t('National Universities').'</strong> - '.t('Frequently asked questions').'</h3><class="costa-rica">'.$imagen."<h4>".$costa_rica->name."</h4>".'</div></div>';
  $accordion_nacional = "<ul class='accordion'>";
  $result = consultar_preguntas($costa_rica);
  while($record = $result->fetchObject()) {
    $accordion_nacional .= '<li><a href="#recent" class="heading">'.$record->field_pregunta_value.'</a><div id="recent">'.$record->field_respuesta_value.'</div></li>';
  }
  $accordion_nacional .= '</ul>';
  $bloque_nacional .= $accordion_nacional;

  //********** ACORDION EXTRANJEROS *******  
  $eu = taxonomy_term_load(14); //EEUU
  $can = taxonomy_term_load(15); //Canada
  $mex = taxonomy_term_load(16); //Mexico
  $esp = taxonomy_term_load(17); //España

  $bloque_ext = '<div id="pf-extrajeros"><h3><strong>'.t('Foreign Universities').'</strong> - '.t('Frequently asked questions').'</h3></div>';

  $accordion_eu = "<ul class='accordion'>";
  $imagen = "<img src='" . $base_url . '/sites/default/files/banderas/' . $eu->field_imagen[LANGUAGE_NONE][0]['filename'] . "'>";
  $bloque_eu = '<div class="eu">'.$imagen."<h4>".$eu->name."</h4>".'</div>';

  $result = consultar_preguntas($eu);
  while($record = $result->fetchObject()) {
    $accordion_eu .= '<li><a href="#recent" class="heading">'.$record->field_pregunta_value.'</a><div id="recent">'.$record->field_respuesta_value.'</div></li>';
  }

  $accordion_eu .= '</ul>';
  $bloque_eu .= $accordion_eu;

  $accordion_can = "<ul class='accordion'>";
  $imagen = "<img src='" . $base_url . '/sites/default/files/banderas/' . $can->field_imagen[LANGUAGE_NONE][0]['filename'] . "'>";
  $bloque_can = '<div class="can">'.$imagen."<h4>".$can->name."</h4>".'</div>';

  $result = consultar_preguntas($can);
  while($record = $result->fetchObject()) {
    $accordion_can .= '<li><a href="#recent" class="heading">'.$record->field_pregunta_value.'</a><div id="recent">'.$record->field_respuesta_value.'</div></li>';
  }

  $accordion_can .= '</ul>';
  $bloque_can .= $accordion_can;

  $accordion_mex = "<ul class='accordion'>";
  $imagen = "<img src='" . $base_url . '/sites/default/files/banderas/' . $mex->field_imagen[LANGUAGE_NONE][0]['filename'] . "'>";
  $bloque_mex = '<div class="mex">'.$imagen."<h4>".$mex->name."</h4>".'</div>';

  $result = consultar_preguntas($mex);
  while($record = $result->fetchObject()) {
    $accordion_mex .= '<li><a href="#recent" class="heading">'.$record->field_pregunta_value.'</a><div id="recent">'.$record->field_respuesta_value.'</div></li>';
  }

  $accordion_mex .= '</ul>';
  $bloque_mex .= $accordion_mex;

  $accordion_esp = "<ul class='accordion'>";
  $imagen = "<img src='" . $base_url . '/sites/default/files/banderas/' . $esp->field_imagen[LANGUAGE_NONE][0]['filename'] . "'>";
  $bloque_esp = '<div class="esp">'.$imagen."<h4>".$esp->name."</h4>".'</div>';

  $result = consultar_preguntas($esp);
  while($record = $result->fetchObject()) {
    $accordion_esp .= '<li><a href="#recent" class="heading">'.$record->field_pregunta_value.'</a><div id="recent">'.$record->field_respuesta_value.'</div></li>';
  }

  $accordion_esp .= '</ul>';
  $bloque_esp .= $accordion_esp;

  $bloque_ext .= $bloque_eu . $bloque_can . $bloque_mex .$bloque_esp;

  return "<h2 class='azul'>".t('Información sobre universidades y el BI')."</h2>".$bloque_nacional . $bloque_ext;
}

function consultar_preguntas($pais){
  $query = db_select('node', 'n');
  //$query->fields('n', array('title'));
  $query->join('field_data_field_pais','p','n.nid = p.entity_id');
  $query->join('field_data_field_preguntas','fdfps','n.nid = fdfps.entity_id');
  $query->join('field_data_field_pregunta','fdfp','fdfp.entity_id = fdfps.field_preguntas_value');
  $query->join('field_data_field_respuesta','fdfr','fdfr.entity_id = fdfps.field_preguntas_value');
  $query->fields('fdfp', array('field_pregunta_value'));
  $query->fields('fdfr', array('field_respuesta_value'));
  $query->condition('n.type','preguntas_frecuentes','=');
  $query->condition('p.field_pais_tid',$pais->tid,'=');
  $result = $query->execute();
  return $result;
}