<?php
/**
* Implements hook_form_alter().
*/
function asobitico_module_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  
  if($form['#id'] == 'views-exposed-form-colegios-block-pin-mapa') {

  dpm($form);
    /*foreach ($form['field_colegio_tid']['#options'] as $term_key => $term) {

      // Check if this isn't the 'ANY' option
      if($term_key !== 'All') {
        // Check if this is a child by looking for '-' as first char in string
        $term_value = reset($term->option);
        if($term_value[0] == '-') {
          unset($form['tid']['#options'][$term_key]);
        }
      }

    }
*/
  }

}